import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Neo-Brutalist Bauhaus Design System
        'on-surface-variant': '#4a4a4a',
        'tertiary-container': '#d6e3ff',
        'secondary-container': '#ffdad6',
        'inverse-primary': '#f5f0e8',
        'surface': '#f5f0e8',
        'primary-container': '#ffcc00',
        'inverse-on-surface': '#f5f0e8',
        'on-primary': '#ffffff',
        'secondary-fixed-dim': '#ffb3ab',
        'secondary-fixed': '#ffdad6',
        'outline-variant': '#d0cbc3',
        'surface-container-high': '#e8e3da',
        'inverse-surface': '#1a1a1a',
        'primary-fixed': '#ffcc00',
        'on-tertiary-fixed': '#1a1a1a',
        'surface-container': '#eee9e0',
        'on-secondary-fixed-variant': '#1a1a1a',
        'tertiary': '#0055ff',
        'on-tertiary-container': '#1a1a1a',
        'on-tertiary': '#ffffff',
        'on-error-container': '#93000a',
        'surface-container-low': '#f2ede5',
        'on-tertiary-fixed-variant': '#1a1a1a',
        'error': '#cc0000',
        'primary-fixed-dim': '#e6b800',
        'secondary': '#e63b2e',
        'on-secondary-fixed': '#1a1a1a',
        'surface-variant': '#e8e3da',
        'error-container': '#ffdad6',
        'outline': '#1a1a1a',
        'on-primary-fixed': '#1a1a1a',
        'surface-tint': '#1a1a1a',
        'on-primary-container': '#1a1a1a',
        'on-primary-fixed-variant': '#1a1a1a',
        'on-background': '#1a1a1a',
        'surface-bright': '#faf7f2',
        'background': '#f5f0e8',
        'on-secondary': '#1a1a1a',
        'surface-dim': '#d6d1c9',
        'tertiary-fixed-dim': '#a8c6ff',
        'on-surface': '#1a1a1a',
        'on-secondary-container': '#1a1a1a',
        'tertiary-fixed': '#d6e3ff',
        'surface-container-highest': '#e2ddd4',
        'surface-container-lowest': '#ffffff',
        'on-error': '#ffffff',
        'primary': '#1a1a1a',
        
        // Legacy support (keep for backward compatibility)
        brand: {
          50: '#EEEDFE',
          100: '#DDD9FD',
          200: '#BCB4FB',
          300: '#9A8EF9',
          400: '#7F77DD',
          500: '#6B63C5',
          600: '#534AB7',
          700: '#3F3889',
          800: '#2B265B',
          900: '#17142E',
          950: '#0B0A17',
        },
        accent: {
          50: '#FAECE7',
          100: '#F5D9CF',
          200: '#EBB39F',
          300: '#E18D6F',
          400: '#D85A30',
          500: '#B94A26',
          600: '#993C1D',
          700: '#7A2E17',
          800: '#5A2011',
          900: '#3B150B',
          950: '#1D0A05',
        },
        sidebar: '#0a0f1e',
        success: '#10b981',
        warning: '#f59e0b',
        danger: '#ef4444',
        info: '#0ea5e9',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Space Grotesk', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
        pill: '9999px',
      },
      borderWidth: {
        thin: '0.5px',
      },
      letterSpacing: {
        tighter: '-0.05em',
        tight: '-0.025em',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-12px)' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        float: 'float 4s ease-in-out infinite',
        'float-delay': 'float 4s ease-in-out 2s infinite',
        'float-delay-2': 'float 4s ease-in-out 1s infinite',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}

export default config
